### ISSUE TITLE
Add some screenshots

### ISSUE THREAD

**Issue by MadLittleMods** [Siecje/hashword#2]
Add some screenshots so I don't have to run it myself to check it out

**Comment by MadLittleMods** [comment]
There is already a screenshot on your personal site that could be used, https://siecje.github.io/

![](https://siecje.github.io/img/hashword.png)

**Comment by Siecje** [comment]
Images have been added to the README https://github.com/Siecje/hashword/commit/37965d5ecbb0a88bb901b85fab822b4fc773ee8b
