### ISSUE TITLE
Firefox version?

### ISSUE THREAD

**Issue by rolltidehero** [Siecje/hashword#3]
Man, I've been looking for something like this ever since I came across SaltThePass.com! I never used it though because there was no browser extension. Now I found Hashword! But I use both Firefox and Chromium browsers, so I was wondering if you could port it to Firefox or if you could guide me on how to do it myself?

Great freakin' job dude!

**Comment by Siecje** [comment]
This isn't a browser extension.

I wouldn't want a browser extension because then you need to trust that nothing is able to see the master password.
